# Generated by Django 4.1.5 on 2023-01-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumematcher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobDescription',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='name',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='requirements',
            field=models.TextField(default='test default'),
        ),
    ]
